/* Generated By:JavaCC: Do not edit this line. IsAriExpConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IsAriExpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int CHAR = 9;
  /** RegularExpression Id. */
  int BEGIN = 10;
  /** RegularExpression Id. */
  int END = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int SEMI = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int ADD = 16;
  /** RegularExpression Id. */
  int DEC = 17;
  /** RegularExpression Id. */
  int MUL = 18;
  /** RegularExpression Id. */
  int DIV = 19;
  /** RegularExpression Id. */
  int LB = 20;
  /** RegularExpression Id. */
  int RB = 21;
  /** RegularExpression Id. */
  int PT = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int ID = 24;
  /** RegularExpression Id. */
  int DIGITS = 25;
  /** RegularExpression Id. */
  int LETTER = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\" \"",
    "\"program\"",
    "\"var\"",
    "\"integer\"",
    "\"real\"",
    "\"char\"",
    "\"begin\"",
    "\"end\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "<NUMBER>",
    "<ID>",
    "<DIGITS>",
    "<LETTER>",
  };

}
