#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[253] =
    {   0,
        0,    0,   95,   93,    1,    1,   50,   79,   93,   39,
       62,   78,   69,   70,   37,   35,   75,   36,   81,   38,
       87,   87,   77,   76,   45,   51,   44,   68,   84,   71,
       72,   64,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   73,
       63,   74,   65,    1,   43,    0,   86,    0,    0,    0,
       48,   59,    0,   54,   40,   87,   52,   41,   53,   80,
        0,   90,   55,    0,    0,    0,    0,   66,   47,   42,
       46,   67,   84,   61,   84,   84,   84,   84,   84,   84,
       33,   84,   84,   84,   84,   84,   84,   27,   84,   84,

       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   60,   49,    0,    0,   56,   85,    0,    0,
       90,   87,   88,    0,   87,   89,   57,   58,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   34,
       84,    5,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
        0,    0,    0,   90,   17,   84,   30,    4,   84,   84,
       84,   84,   28,   14,   84,   84,   25,    9,    2,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,    3,   84,   84,    0,    0,   24,   22,   84,

       84,   84,   84,    6,   84,   84,   84,   83,    8,   84,
       84,   84,   84,   84,   84,   13,   84,   84,   32,    0,
        0,   84,   84,    7,   20,   82,   84,   26,   11,   16,
       18,   12,   29,   84,   84,   84,   91,    0,   84,   31,
       84,   15,   84,   84,   91,   92,   23,   19,   10,   21,
       92,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   27,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       32,    1,   33,   34,   30,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   30,   44,   45,   46,   47,
       48,   49,   30,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[261] =
    {   0,
        0,    0,  333,  334,   61,   63,  308,  326,   29,  323,
       60,    0,  334,  334,  305,   56,  334,   63,  334,   73,
       82,   75,  334,  334,   47,  304,   81,  334,    0,  334,
      334,  303,  273,  275,   44,   60,   70,   64,  276,   49,
      275,  287,  271,  281,   82,  262,  271,  269,  274,  334,
       79,  334,  334,  120,  334,  310,  309,  274,  265,  287,
      334,  334,  301,  334,  334,  111,  334,  334,  334,  334,
      297,    0,  334,  123,  114,  133,    0,  284,  334,  334,
      334,  283,    0,  334,  254,  266,  253,  268,  255,  261,
      247,  248,  245,  245,  248,  245,  242,    0,  241,  245,

      248,  247,   95,  254,  240,   87,   85,  244,  237,  106,
      111,  242,  334,  334,  244,  246,  334,  334,  143,  146,
        0,  146,  143,  149,  152,    0,  334,  334,  234,  246,
      241,  229,  122,  243,  241,  237,  229,  235,  238,    0,
      224,    0,  230,  223,  222,  225,  214,  219,  215,  217,
      224,  210,  208,  208,  220,  210,  214,  218,  220,  209,
      210,  207,  164,  334,    0,  207,    0,    0,  198,  206,
      195,  202,    0,    0,  196,  193,    0,    0,    0,  192,
      192,  192,  201,  188,  200,  190,  194,  199,  198,  196,
      186,  191,    0,  179,  191,  182,  175,    0,    0,  180,

      181,  186,  177,    0,  183,  170,  174,    0,    0,  182,
      179,  181,  162,  167,  165,    0,  153,  149,    0,  148,
      146,  130,  130,    0,    0,    0,  141,    0,    0,    0,
        0,    0,    0,  139,  139,  132,    0,  120,  105,    0,
       66,    0,   69,   38,    0,    0,    0,    0,    0,    0,
        0,  334,  185,  190,  192,  197,  202,   69,  207,  212
    } ;

static const flex_int16_t yy_def[261] =
    {   0,
      252,    1,  252,  252,  252,  252,  252,  253,  252,  252,
      252,  254,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  255,  252,
      252,  252,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  252,
      252,  252,  252,  252,  252,  253,  253,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      256,  257,  252,  252,  252,  252,  258,  252,  252,  252,
      252,  252,  255,  252,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  252,  252,  252,  252,  252,  252,  256,  256,
      257,  252,  252,  252,  252,  258,  252,  252,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      252,  252,  256,  252,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  252,  252,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  252,
      252,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  259,  252,  255,  255,
      255,  255,  255,  255,  259,  260,  255,  255,  255,  255,
      260,    0,  252,  252,  252,  252,  252,  252,  252,  252
    } ;

static const flex_int16_t yy_nxt[397] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   29,   40,   29,   41,   42,   29,   29,   43,   44,
       45,   46,   47,   48,   49,   29,   29,   29,   50,   51,
       52,   53,   54,   54,   54,   54,   58,   61,   65,   78,
       79,   59,  126,   66,   66,   66,  250,   68,   87,   67,
       66,   66,   66,   62,   71,   88,   69,   70,   98,   72,
       74,   89,   66,   66,   66,   99,   73,   74,   90,   66,

       66,   66,  113,   76,   81,   82,  249,   91,   95,   75,
       76,   96,   77,   76,   92,  248,   93,   75,  104,  152,
       76,   54,   54,  105,  106,   94,   74,  150,   66,   66,
       66,  123,  123,  107,  153,  146,  108,   77,  114,   76,
      122,  122,  122,  247,  151,  124,  147,  124,  156,   76,
      125,  125,  125,  158,  120,  159,  157,  120,  246,  163,
      123,  123,  164,  122,  122,  122,  125,  125,  125,  125,
      125,  125,  169,  170,   76,  120,  244,  243,  242,  241,
      163,  240,  239,  238,   76,   56,  237,   56,   56,   56,
       63,  236,   63,   63,   63,   83,   83,  119,  119,  235,

      119,  119,  121,  234,  121,  121,  121,  245,  233,  245,
      245,  245,  251,  232,  251,  251,  251,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  168,  167,
      166,  165,  162,  161,  160,  155,  154,  149,  148,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,

      134,  133,  132,  131,  130,  129,  128,  127,  120,  118,
      117,  116,  115,   57,   57,  112,  111,  110,  109,  103,
      102,  101,  100,   97,   86,   85,   84,   80,   64,   60,
       57,   55,  252,    3,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252

    } ;

static const flex_int16_t yy_chk[397] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,    9,   11,   16,   25,
       25,    9,  258,   16,   16,   16,  244,   18,   35,   16,
       18,   18,   18,   11,   20,   35,   18,   18,   40,   20,
       22,   35,   22,   22,   22,   40,   20,   21,   36,   21,

       21,   21,   51,   22,   27,   27,  243,   36,   38,   21,
       21,   38,   21,   22,   37,  241,   37,   21,   45,  107,
       21,   54,   54,   45,   45,   37,   66,  106,   66,   66,
       66,   75,   75,   45,  107,  103,   45,   21,   51,   66,
       74,   74,   74,  239,  106,   76,  103,   76,  110,   66,
       76,   76,   76,  111,  119,  111,  110,  120,  238,  119,
      123,  123,  120,  122,  122,  122,  124,  124,  124,  125,
      125,  125,  133,  133,  122,  163,  236,  235,  234,  227,
      163,  223,  222,  221,  122,  253,  220,  253,  253,  253,
      254,  218,  254,  254,  254,  255,  255,  256,  256,  217,

      256,  256,  257,  215,  257,  257,  257,  259,  214,  259,
      259,  259,  260,  213,  260,  260,  260,  212,  211,  210,
      207,  206,  205,  203,  202,  201,  200,  197,  196,  195,
      194,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  176,  175,  172,  171,  170,  169,
      166,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  141,  139,  138,  137,  136,  135,  134,  132,  131,
      130,  129,  116,  115,  112,  109,  108,  105,  104,  102,
      101,  100,   99,   97,   96,   95,   94,   93,   92,   91,

       90,   89,   88,   87,   86,   85,   82,   78,   71,   63,
       60,   59,   58,   57,   56,   49,   48,   47,   46,   44,
       43,   42,   41,   39,   34,   33,   32,   26,   15,   10,
        8,    7,    3,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex_ana.l"
#line 2 "lex_ana.l"
    #include<stdio.h>
    /*definitions of manifest constants*/
    /* KEYWORD */
    #define ID          0
    #define cT          1
    #define sT          2
    #define NUMBER      3

    #define MAIN        4
    #define VOID        5
    #define CHAR        6
    #define INT         7
    #define FLOAT       8
    #define DOUBLE      9

    #define SHORT       10
    #define LONG        11
    #define UNSG        12
    #define SG          13

    #define STRUCT      14
    #define UNION       15
    #define ENUM        16
    #define TYPEDEF     17
    #define SIZEOF      18

    #define AUTO        19
    #define STATIC      20
    #define REGISTER    21
    #define EXTERN      22
    #define VOLATILE    23
    #define CONST       24

    #define CONTINUE    25
    #define BREAK       26
    #define GOTO        27
    #define RETURN      28

    #define IF          29
    #define ELSE        30
    #define SWITCH      31
    #define CASE        32
    #define DEFAULT     33 

    #define WHILE       34
    #define DO          35
    #define FOR         36

    /* OPERATION and DELIMITERS */
    #define ADD         37 
    #define DEC         38
    #define MUL         39
    #define DIV         40
    #define MOD         41
    #define INCR        42
    #define DECR        43

    #define EQ          44
    #define NEQ         45
    #define GT          46
    #define LT          47
    #define GE          48
    #define LE          49

    #define LOG_AND     50
    #define LOG_OR      51
    #define LOG_NOT     52 

    #define ASM         53
    #define ADD_ASM     54
    #define DEC_ASM     55
    #define MUL_ASM     56
    #define DIV_ASM     57
    #define MOD_ASM     58
    #define LSF_ASM     59
    #define RSF_ASM     60
    #define BN_AND_ASM  61
    #define BN_OR_ASM   62
    #define BN_XOR_ASM  63

    #define BN_AND      64
    #define BN_OR       65
    #define BN_XOR      66
    #define BN_REVS     67
    #define LSF         68
    #define RSF         69
    #define QM          70

    #define LP          71
    #define RP          72
    #define LBK         73
    #define RBK         74
    #define LBC         75
    #define RBC         76

    #define COMMA       77
    #define SMI         78
    #define COLON       79
    #define SQU         80
    #define DQU         81

    /* OTHER */
    #define PT          82
    #define SCF         83

    #define INT_BIN     84
    #define INT_HEX     85

    #define PNT         86
    #define ARROW       87

    #define COMMENT     96
    #define DF          97
    #define IFILE       98
    #define ERR         99

#line 732 "lex.yy.c"
#line 733 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 138 "lex_ana.l"

#line 952 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 334 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 139 "lex_ana.l"
{;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 140 "lex_ana.l"
{printf("%d     MAIN      %s\n", MAIN, yytext); return MAIN;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 141 "lex_ana.l"
{printf("%d     VOID      %s\n", VOID, yytext); return VOID;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 142 "lex_ana.l"
{printf("%d     CHAR      %s\n", CHAR, yytext); return CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 143 "lex_ana.l"
{printf("%d     INT       %s\n", INT, yytext); return INT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 144 "lex_ana.l"
{printf("%d     FLOAT     %s\n", FLOAT, yytext); return FLOAT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 145 "lex_ana.l"
{printf("%d     DOUBLE    %s\n", DOUBLE, yytext); return DOUBLE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 147 "lex_ana.l"
{printf("%d    SHORT     %s\n", SHORT, yytext); return SHORT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 148 "lex_ana.l"
{printf("%d    LONG      %s\n", LONG, yytext); return LONG;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 149 "lex_ana.l"
{printf("%d    UNSIGNED  %s\n", UNSG, yytext); return UNSG;} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 150 "lex_ana.l"
{printf("%d    SIGNED    %s\n", SG, yytext); return SG;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 152 "lex_ana.l"
{printf("%d    STRUCT    %s\n", STRUCT, yytext); return STRUCT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 153 "lex_ana.l"
{printf("%d    UNION     %s\n", UNION, yytext); return UNION;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 154 "lex_ana.l"
{printf("%d    ENUM      %s\n", ENUM, yytext); return ENUM;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 155 "lex_ana.l"
{printf("%d    TYPEDEF   %s\n", TYPEDEF, yytext); return TYPEDEF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 156 "lex_ana.l"
{printf("%d    SIZEOF    %s\n", SIZEOF, yytext); return SIZEOF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 158 "lex_ana.l"
{printf("%d    AUTO      %s\n", AUTO, yytext); return AUTO;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 159 "lex_ana.l"
{printf("%d    STATIC    %s\n", STATIC, yytext); return STATIC;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 160 "lex_ana.l"
{printf("%d    REGISTER  %s\n", REGISTER, yytext); return REGISTER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 161 "lex_ana.l"
{printf("%d    EXTERN    %s\n", EXTERN, yytext); return EXTERN;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 162 "lex_ana.l"
{printf("%d    VOLATILE  %s\n", VOLATILE, yytext); return VOLATILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 163 "lex_ana.l"
{printf("%d    CONST     %s\n", CONST, yytext); return CONST;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 165 "lex_ana.l"
{printf("%d    CONTINUE  %s\n", CONTINUE, yytext); return CONTINUE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 166 "lex_ana.l"
{printf("%d    BREAK     %s\n", BREAK, yytext); return BREAK;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 167 "lex_ana.l"
{printf("%d    GOTO      %s\n", GOTO, yytext); return GOTO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 168 "lex_ana.l"
{printf("%d    RETURN    %s\n", RETURN, yytext); return RETURN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 170 "lex_ana.l"
{printf("%d    IF        %s\n", IF, yytext); return IF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 171 "lex_ana.l"
{printf("%d    ELSE      %s\n", ELSE, yytext); return ELSE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 172 "lex_ana.l"
{printf("%d    SWITCH    %s\n", SWITCH, yytext); return SWITCH;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 173 "lex_ana.l"
{printf("%d    CASE      %s\n", CASE, yytext); return CASE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 174 "lex_ana.l"
{printf("%d    DEFAULT   %s\n", DEFAULT, yytext); return DEFAULT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 176 "lex_ana.l"
{printf("%d    WHILE     %s\n", WHILE, yytext); return WHILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 177 "lex_ana.l"
{printf("%d    DO        %s\n", DO, yytext); return DO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 178 "lex_ana.l"
{printf("%d    FOR       %s\n", FOR, yytext); return FOR;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 181 "lex_ana.l"
{printf("%d    +         %s\n", ADD, yytext); return ADD;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 182 "lex_ana.l"
{printf("%d    -         %s\n", DEC, yytext); return DEC;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 183 "lex_ana.l"
{printf("%d    *         %s\n", MUL, yytext); return MUL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 184 "lex_ana.l"
{printf("%d    /         %s\n", DIV, yytext); return DIV;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 185 "lex_ana.l"
{printf("%d    %%         %s\n", MOD, yytext); return MOD;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 186 "lex_ana.l"
{printf("%d    ++        %s\n", INCR, yytext); return INCR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 187 "lex_ana.l"
{printf("%d    --        %s\n", DECR, yytext); return DECR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 189 "lex_ana.l"
{printf("%d    ==        %s\n", EQ, yytext); return EQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 190 "lex_ana.l"
{printf("%d    !=        %s\n", NEQ, yytext); return NEQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 191 "lex_ana.l"
{printf("%d    >         %s\n", GT, yytext); return GT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 192 "lex_ana.l"
{printf("%d    <         %s\n", LT, yytext); return LT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 193 "lex_ana.l"
{printf("%d    >=        %s\n", GE, yytext); return GE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 194 "lex_ana.l"
{printf("%d    <=        %s\n", LE, yytext); return LE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 196 "lex_ana.l"
{printf("%d    &&        %s\n", LOG_AND, yytext); return LOG_AND;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 197 "lex_ana.l"
{printf("%d    ||        %s\n", LOG_OR, yytext); return LOG_OR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 198 "lex_ana.l"
{printf("%d    !         %s\n", LOG_NOT, yytext); return LOG_NOT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 200 "lex_ana.l"
{printf("%d    =         %s\n", ASM, yytext); return ASM;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 201 "lex_ana.l"
{printf("%d    +=        %s\n", ADD_ASM, yytext); return ADD_ASM;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 202 "lex_ana.l"
{printf("%d    -=        %s\n", DEC_ASM, yytext); return DEC_ASM;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 203 "lex_ana.l"
{printf("%d    *=        %s\n", MUL_ASM, yytext); return MUL_ASM;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 204 "lex_ana.l"
{printf("%d    /=        %s\n", DIV_ASM, yytext); return DIV_ASM;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 205 "lex_ana.l"
{printf("%d    %%=        %s\n", MOD_ASM, yytext); return MOD_ASM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 206 "lex_ana.l"
{printf("%d    <<=       %s\n", LSF_ASM, yytext); return LSF_ASM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 207 "lex_ana.l"
{printf("%d    >>=       %s\n", RSF_ASM, yytext); return RSF_ASM;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 208 "lex_ana.l"
{printf("%d    &=        %s\n", BN_AND_ASM, yytext); return BN_AND_ASM;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 209 "lex_ana.l"
{printf("%d    |=        %s\n", BN_OR_ASM, yytext); return BN_OR_ASM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 210 "lex_ana.l"
{printf("%d    ^=        %s\n", BN_XOR_ASM, yytext); return BN_XOR_ASM;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 212 "lex_ana.l"
{printf("%d    &         %s\n", BN_AND, yytext); return BN_AND;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 213 "lex_ana.l"
{printf("%d    |         %s\n", BN_OR, yytext); return BN_OR;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 214 "lex_ana.l"
{printf("%d    ^         %s\n", BN_XOR, yytext); return BN_XOR;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 215 "lex_ana.l"
{printf("%d    ~         %s\n", BN_REVS, yytext); return BN_REVS;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 216 "lex_ana.l"
{printf("%d    <<        %s\n", LSF, yytext); return LSF;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 217 "lex_ana.l"
{printf("%d    >>        %s\n", RSF, yytext); return RSF;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 218 "lex_ana.l"
{printf("%d    ?         %s\n", QM, yytext); return QM;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 220 "lex_ana.l"
{printf("%d    (         %s\n", LP, yytext); return LP;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 221 "lex_ana.l"
{printf("%d    )         %s\n", RP, yytext); return RP;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 222 "lex_ana.l"
{printf("%d    [         %s\n", LBK, yytext); return LBK;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 223 "lex_ana.l"
{printf("%d    ]         %s\n", RBK, yytext); return RBK;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 224 "lex_ana.l"
{printf("%d    {         %s\n", LBC, yytext); return LBC;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 225 "lex_ana.l"
{printf("%d    }         %s\n", RBC, yytext); return RBC;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 227 "lex_ana.l"
{printf("%d    ,         %s\n", COMMA, yytext); return COMMA;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 228 "lex_ana.l"
{printf("%d    ;         %s\n", SMI, yytext); return SMI;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 229 "lex_ana.l"
{printf("%d    :         %s\n", COLON, yytext); return COLON;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 230 "lex_ana.l"
{printf("%d    '         %s\n", SQU, yytext); return SQU;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 231 "lex_ana.l"
{printf("%d    \"         %s\n", DQU, yytext); return DQU;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 233 "lex_ana.l"
{printf("%d    ->        %s\n", ARROW, yytext); return ARROW;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 234 "lex_ana.l"
{printf("%d    .         %s\n", PNT, yytext); return PNT;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 236 "lex_ana.l"
{printf("%d    PRINTF    %s\n", PT, yytext); return PT;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 237 "lex_ana.l"
{printf("%d    SCANF     %s\n", SCF, yytext); return SCF;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 239 "lex_ana.l"
{printf("%d     ID        %s\n", ID, yytext); return ID;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 240 "lex_ana.l"
{printf("%d     cT        %s\n", cT, yytext); return cT;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 241 "lex_ana.l"
{printf("%d     sT        %s\n", sT, yytext); return sT;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 242 "lex_ana.l"
{printf("%d     NUMBER    %s\n", NUMBER, yytext); return NUMBER;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 244 "lex_ana.l"
{printf("%d    INT_BIN   %s\n", INT_BIN, yytext); return INT_BIN;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 245 "lex_ana.l"
{printf("%d    INT_HEX   %s\n", INT_HEX, yytext); return INT_HEX;}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 247 "lex_ana.l"
{printf("%d    COMMENT   %s\n", COMMENT, yytext); return COMMENT;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 248 "lex_ana.l"
{printf("%d    DF        %s\n", DF, yytext); return DF;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 249 "lex_ana.l"
{printf("%d    FILE      %s\n", IFILE, yytext); return IFILE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 251 "lex_ana.l"
{printf("%d    ERR       %s\n", ERR, yytext); return ERR;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 253 "lex_ana.l"
{printf("END OF FILE.\n"); return -1;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 255 "lex_ana.l"
ECHO;
	YY_BREAK
#line 1485 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 252);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 255 "lex_ana.l"



int yywrap (){
    return 1;
}

void textout(int r){
    switch(r){
        case ID:        fprintf(yyout,"< %d  , %s >\n", ID, yytext);  break;
        case cT:        fprintf(yyout,"< %d  , %s >\n", cT, yytext);  break;
        case sT:        fprintf(yyout,"< %d  , %s >\n", sT, yytext);  break;
        case NUMBER:    fprintf(yyout,"< %d  , %s >\n", NUMBER, yytext);  break;

        case MAIN:      fprintf(yyout,"< %d  , %s >\n", MAIN, yytext);  break;
        case VOID:      fprintf(yyout,"< %d  , %s >\n", VOID, yytext);  break;
        case CHAR:      fprintf(yyout,"< %d  , %s >\n", CHAR, yytext);  break;
        case INT:       fprintf(yyout,"< %d  , %s >\n", INT, yytext);  break;
        case FLOAT:     fprintf(yyout,"< %d  , %s >\n", FLOAT, yytext);  break;
        case DOUBLE:    fprintf(yyout,"< %d  , %s >\n", DOUBLE, yytext);  break;
        
        case SHORT:     fprintf(yyout,"< %d , %s >\n", SHORT, yytext);  break;
        case LONG:      fprintf(yyout,"< %d , %s >\n", LONG, yytext);  break;
        case UNSG:      fprintf(yyout,"< %d , %s >\n", UNSG, yytext);  break;
        case SG:        fprintf(yyout,"< %d , %s >\n", SG, yytext);  break;
        
        case STRUCT:    fprintf(yyout,"< %d , %s >\n", STRUCT, yytext);  break;
        case UNION:     fprintf(yyout,"< %d , %s >\n", UNION, yytext);  break;
        case ENUM:      fprintf(yyout,"< %d , %s >\n", ENUM, yytext);  break;
        case TYPEDEF:   fprintf(yyout,"< %d , %s >\n", TYPEDEF, yytext);  break;
        case SIZEOF:    fprintf(yyout,"< %d , %s >\n", SIZEOF, yytext);  break;

        case AUTO:      fprintf(yyout,"< %d , %s >\n", AUTO, yytext);  break;
        case STATIC:    fprintf(yyout,"< %d , %s >\n", STATIC, yytext);  break;
        case REGISTER:  fprintf(yyout,"< %d , %s >\n", REGISTER, yytext);  break;
        case EXTERN:    fprintf(yyout,"< %d , %s >\n", EXTERN, yytext);  break;
        case VOLATILE:  fprintf(yyout,"< %d , %s >\n", VOLATILE, yytext);  break;
        case CONST:     fprintf(yyout,"< %d , %s >\n", CONST, yytext);  break;

        case CONTINUE:  fprintf(yyout,"< %d , %s >\n", CONTINUE, yytext);  break;
        case BREAK:     fprintf(yyout,"< %d , %s >\n", BREAK, yytext);  break;
        case GOTO:      fprintf(yyout,"< %d , %s >\n", GOTO, yytext);  break;
        case RETURN:    fprintf(yyout,"< %d , %s >\n", RETURN, yytext);  break;

        case IF:        fprintf(yyout,"< %d , %s >\n", IF, yytext);  break;
        case ELSE:      fprintf(yyout,"< %d , %s >\n", ELSE, yytext);  break;
        case SWITCH:    fprintf(yyout,"< %d , %s >\n", SWITCH, yytext);  break;
        case CASE:      fprintf(yyout,"< %d , %s >\n", CASE, yytext);  break;
        case DEFAULT:   fprintf(yyout,"< %d , %s >\n", DEFAULT, yytext);  break;

        case WHILE:     fprintf(yyout,"< %d , %s >\n", WHILE, yytext);  break;
        case DO:        fprintf(yyout,"< %d , %s >\n", DO, yytext);  break;
        case FOR:       fprintf(yyout,"< %d , %s >\n", FOR, yytext);  break;

        case ADD:       fprintf(yyout,"< %d , %s >\n", ADD, yytext);  break;
        case DEC:       fprintf(yyout,"< %d , %s >\n", DEC, yytext);  break;
        case MUL:       fprintf(yyout,"< %d , %s >\n", MUL, yytext);  break;
        case DIV:       fprintf(yyout,"< %d , %s >\n", DIV, yytext);  break;
        case MOD:       fprintf(yyout,"< %d , %s >\n", MOD, yytext);  break;
        case INCR:      fprintf(yyout,"< %d , %s >\n", INCR, yytext);  break;
        case DECR:      fprintf(yyout,"< %d , %s >\n", DECR, yytext);  break;

        case EQ:        fprintf(yyout,"< %d , %s >\n", EQ, yytext);  break;
        case NEQ:       fprintf(yyout,"< %d , %s >\n", NEQ, yytext);  break;
        case GT:        fprintf(yyout,"< %d , %s >\n", GT, yytext);  break;
        case LT:        fprintf(yyout,"< %d , %s >\n", LT, yytext);  break;
        case GE:        fprintf(yyout,"< %d , %s >\n", GE, yytext);  break;
        case LE:        fprintf(yyout,"< %d , %s >\n", LE, yytext);  break;

        case LOG_AND:   fprintf(yyout,"< %d , %s >\n", LOG_AND, yytext);  break;
        case LOG_OR:    fprintf(yyout,"< %d , %s >\n", LOG_OR, yytext);  break;
        case LOG_NOT:   fprintf(yyout,"< %d , %s >\n", LOG_NOT, yytext);  break;

        case ASM:       fprintf(yyout,"< %d , %s >\n", ASM, yytext);  break;
        case ADD_ASM:   fprintf(yyout,"< %d , %s >\n", ADD_ASM, yytext);  break;
        case DEC_ASM:   fprintf(yyout,"< %d , %s >\n", DEC_ASM, yytext);  break;
        case MUL_ASM:   fprintf(yyout,"< %d , %s >\n", MUL_ASM, yytext);  break;
        case DIV_ASM:   fprintf(yyout,"< %d , %s >\n", DIV_ASM, yytext);  break;
        case MOD_ASM:   fprintf(yyout,"< %d , %s >\n", MOD_ASM, yytext);  break;
        case LSF_ASM:   fprintf(yyout,"< %d , %s >\n", LSF_ASM, yytext);  break;
        case RSF_ASM:   fprintf(yyout,"< %d , %s >\n", RSF_ASM, yytext);  break;
        case BN_AND_ASM:fprintf(yyout,"< %d , %s >\n", BN_AND_ASM, yytext);  break;
        case BN_OR_ASM: fprintf(yyout,"< %d , %s >\n", BN_OR_ASM, yytext);  break;
        case BN_XOR_ASM:fprintf(yyout,"< %d , %s >\n", BN_XOR_ASM, yytext);  break;
        
        case BN_AND:    fprintf(yyout,"< %d , %s >\n", BN_AND, yytext);  break;
        case BN_OR:     fprintf(yyout,"< %d , %s >\n", BN_OR, yytext);  break;
        case BN_XOR:    fprintf(yyout,"< %d , %s >\n", BN_XOR, yytext);  break;
        case BN_REVS:   fprintf(yyout,"< %d , %s >\n", BN_REVS, yytext);  break;
        case LSF:       fprintf(yyout,"< %d , %s >\n", LSF, yytext);  break;
        case RSF:       fprintf(yyout,"< %d , %s >\n", RSF, yytext);  break;
        case QM:        fprintf(yyout,"< %d , %s >\n", QM, yytext);  break;

        case LP:        fprintf(yyout,"< %d , %s >\n", LP, yytext);  break;
        case RP:        fprintf(yyout,"< %d , %s >\n", RP, yytext);  break;
        case LBK:       fprintf(yyout,"< %d , %s >\n", LBK, yytext);  break;
        case RBK:       fprintf(yyout,"< %d , %s >\n", RBK, yytext);  break;
        case LBC:       fprintf(yyout,"< %d , %s >\n", LBC, yytext);  break;
        case RBC:       fprintf(yyout,"< %d , %s >\n", RBC, yytext);  break;

        case COMMA:     fprintf(yyout,"< %d , %s >\n", COMMA, yytext);  break;
        case SMI:       fprintf(yyout,"< %d , %s >\n", SMI, yytext);  break;
        case COLON:     fprintf(yyout,"< %d , %s >\n", COLON, yytext);  break;
        case SQU:       fprintf(yyout,"< %d , %s >\n", SQU, yytext);  break;
        case DQU:       fprintf(yyout,"< %d , %s >\n", DQU, yytext);  break;

        case PT:        fprintf(yyout,"< %d , %s >\n", PT, yytext);  break;
        case SCF:       fprintf(yyout,"< %d , %s >\n", SCF, yytext);  break;
        
        case INT_BIN:   fprintf(yyout,"< %d , %s >\n", INT_BIN, yytext);  break;
        case INT_HEX:   fprintf(yyout,"< %d , %s >\n", INT_HEX, yytext);  break;

        case PNT:       fprintf(yyout,"< %d , %s >\n", PNT, yytext);  break;
        case ARROW:     fprintf(yyout,"< %d , %s >\n", ARROW, yytext);  break;

        case COMMENT:   fprintf(yyout,"< %d , COMMENT >\n", COMMENT);  break;
        case DF:        fprintf(yyout,"< %d , %s >\n", DF, yytext);  break;
        case IFILE:     fprintf(yyout,"< %d , %s >\n", IFILE, yytext);  break;
        case ERR:       fprintf(yyout,"< %d , %s >\n", ERR, yytext);  break;
        
        default: break;
    }
    return;
}

int main (int argc, char ** argv){
    
    printf("TOKEN KEYWORD   TOKEN VALUE\n");
    int c;
	if (argc>=2){
	    if ((yyin = fopen(argv[1], "r")) == NULL){
	    printf("Can't open file %s\n", argv[1]);
	    return 1;
        }
        if (argc>=3){
            yyout=fopen(argv[2], "w");
	    }
	}

	while (1){
        c = yylex();
        textout(c);
        if(c == -1)
            break;
	}
    
	if(argc>=2){
	    fclose(yyin);
	    if (argc>=3) fclose(yyout);
	}
	return 0;

}

